Repository projectdiscovery/chaos-client, pull requests merged in 2020-05, with the labels that each got.

#2 increased timeout for uploads
  README.md
  pkg/chaos/chaos.go
Labels: bug, enhancement

#5 Adding stdin support to upload data to chaos dataset
  internal/runner/options.go
  internal/runner/runner.go
Labels: enhancement

#10 fixed small typo
  internal/runner/runner.go
Labels: bug

#11 version bump
  go.mod
  go.sum
  internal/runner/banner.go
Labels: enhancement
